// flow-typed signature: 617afb8beac2a21a8f73936c03919aa3
// flow-typed version: <<STUB>>/expo-app-loading_v^1.0.1/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo-app-loading'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo-app-loading' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo-app-loading/build/AppLoading' {
  declare module.exports: any;
}

declare module 'expo-app-loading/build/AppLoadingNativeWrapper' {
  declare module.exports: any;
}

declare module 'expo-app-loading/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo-app-loading/build/AppLoading.js' {
  declare module.exports: $Exports<'expo-app-loading/build/AppLoading'>;
}
declare module 'expo-app-loading/build/AppLoadingNativeWrapper.js' {
  declare module.exports: $Exports<'expo-app-loading/build/AppLoadingNativeWrapper'>;
}
declare module 'expo-app-loading/build/index' {
  declare module.exports: $Exports<'expo-app-loading/build'>;
}
declare module 'expo-app-loading/build/index.js' {
  declare module.exports: $Exports<'expo-app-loading/build'>;
}
